#ifndef __UTIL__NAMES__H_INCLUDED__
#define __UTIL__NAMES__H_INCLUDED__

#define NAMES_CASHIERQ_FIFO "cashierq_fifo"

#define NAMES_SEM_CASHIER_AMOUNT 4

#define NAMES_SEM_CASHIER_CASHIER 0
#define NAMES_SEM_CASHIER_CHILD 1
#define NAMES_SEM_CASHIER_MONEY 2
#define NAMES_SEM_CASHIER_CHANGE 3



#endif
