#ifndef __UTIL__NAMES__H_INCLUDED__
#define __UTIL__NAMES__H_INCLUDED__

#define NAMES_CASHIERQ_FIFO "cashierq_fifo"
#define NAMES_CARROUSELQ_FIFO "carrouselq_fifo"
#define NAMES_EXITQ_FIFO "exitq_fifo"
#define NAMES_BALANCE_FILE "balance"

#define NAMES_SEM_CASHIER_AMOUNT 4

#define NAMES_SEM_CASHIER_CASHIER 0
#define NAMES_SEM_CASHIER_CHILD 1
#define NAMES_SEM_CASHIER_MONEY 2
#define NAMES_SEM_CASHIER_CHANGE 3

#define NAMES_SEM_CARROUSEL_AMOUNT 1

#define NAMES_SEM_CARROUSEL_ENTRANCE 0

#endif
